name: hrl-tb
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.6
  - pytorch-gpu=1.3.1
  - matplotlib=2.2.3
  - networkx=2.2
  - tensorflow=1.15
  - pip=21.0.1
  - transitions=0.8.7
  - nltk=3.5
  - pandas=1.1.3
  - ipykernel=5.3.4
  - transformers=4.4.2
  - pip:
      - gym==0.17.2
      - opencv-python==4.2.0.32