name: hrl-tb
dependencies:
  - pytorch-gpu=1.3.1
  - matplotlib==2.2.3
  - networkx==2.2
  - pip:
      - bert-embedding==1.0.1
      - gym==0.17.2
      - opencv-python==4.2.0.32
      - numpy 1.20.1